name: protopipe-dev
channels:
  - defaults
dependencies:
  - python >=3.7,<3.9
  - pip
  - conda-forge::ctapipe=0.11.0
  - conda-forge::gammapy=0.18.2
  - astropy>=4.0.1
  - h5py=2
  - ipython
  - jupyterlab>=3.1.10
  - jupyter-book
  - conda-forge::nbsphinx
  - notebook
  - numpydoc
  - pandas>=1.0.0
  - pytest
  - conda-forge::sphinx-automodapi
  - sphinx_rtd_theme
  - conda-forge::sphinx-issues
  - pip:
      - papermill
      - pyirf==0.5.0
      - pytest-dependency
