name: protopipe-dev
channels:
  - defaults
  - conda-forge
dependencies:
  # Python & PyPI
  - python=3.8
  - pip
  # Base dependencies
  - ctapipe=0.11.0
  - gammapy=0.18.2
  - pandas=1.3.5
  - scikit-learn=1.0.2
  # Testing and code style
  - pytest
  - pytest-dependency
  - codecov
  - pytest-cov
  - black
  # Documentation
  - pydata-sphinx-theme
  - sphinx-automodapi
  - numpydoc
  - sphinx-issues
  # Benchmarking
  - papermill
  - jupyterlab>=3.1.10
  - jupyter-book
  - pip:
      - pyirf==0.5.0
